modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="mcga"
version="${file.jarVersion}"
displayName="Mcga"
authors="PoseidonLi"
description='''
Make copper great again!
'''
[[dependencies.mcga]]
   modId="forge"
   mandatory=true
   versionRange="[37,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mcga]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,1.18)"
   ordering="NONE"
   side="BOTH"
