modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
[[mods]]
modId="mcga"
version="${file.jarVersion}"
displayName="Mcga"
authors="PoseidonLi"
description='''
Make copper great again!
'''
[[dependencies.mcga]]
   modId="forge"
   mandatory=true
   versionRange="[38,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mcga]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18,1.19)"
   ordering="NONE"
   side="BOTH"
